### ISSUE TITLE
Some commands need spaces added

### ISSUE THREAD

**Issue by mooman219** [ivandardi/RustbotPython#11]
Adding a space after the end of the word like here would make sense: https://github.com/ivandardi/RustbotPython/blob/b4440d97b48b8b14ce193fb0f8d7786a665b6e42/bot/__init__.py#L91

**Comment by ivandardi** [comment]
Fixed on commit https://github.com/ivandardi/RustbotPython/commit/f1280407665253a199794f84c1afbe626908acc9
